import SideBar from '@/components/SideBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar />
        <div className='ml-64 w-full md:w-[calc(100%-256px)]  min-h-screen bg-gray-50'> 
        {children}
        </div>
        </body>
    </html>
  )
}
